import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import data, { inventory } from "../data/inventory.js";
import styles from "@/styles/Home.module.css";
import Product from "@/components/products";
import Link from "next/link";


export default function Home() {
const [data,setData] = useState([...inventory.clothing])
  const[categoryValue, setCategoryValue] = useState();
  const[gender, setGender] = useState();

  // function that passes over a value
    // if its hoodies ...
    //
 

  return (
    <>
      <Head>
        <title>Geared Up Online Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Geared Up</h1>
      </div>

      <main className={styles.main}>
        <div className={styles.description}>
          <div className={styles.data}>
            <h2>Filtered By:</h2>
            <button onClick={() => console.log("test")}>test</button>
          
        <h4 onClick={() => {setCategoryValue(null), setGender("men")}}>Men</h4>
        <ul>
          <li onClick={() => {setCategoryValue("hoodies"), setGender("men")}}>Hoodies</li>
          <li>Jacket</li>
          <li>Headger</li>
        </ul>


        <h4>Female</h4>
        <ul>

          <li>Hoodies</li>
          <li>Jacket</li>
          <li>Headger</li>
        </ul>
   
        <h4>Unisex</h4>
        <ul>
   
          <li>Hoodies</li>
          <li>Jacket</li>
          <li>Headger</li>
        </ul>

          </div>
        </div>

        {data &&
          data.map((i, index) => {    
              console.log(i)
            if (i.sex.toLowerCase() === gender && i.category.toLowerCase() === categoryValue){
              return (
                <div key={index}>
                  <Product img={i.image} tag={i.title} price={i.cost} />
                  {i.title}
                </div>
              );

            }else if(i.sex.toLowerCase() === gender && categoryValue == null){
              return(
                <div key = {index}>
                  <Product 
                  img={i.image}/>
                </div>
              )
      
            }
          })}
      </main>
    </>
  );
}
